// Enhanced location data with states/counties for ALL countries

export const COUNTRY_STATES = {
    // Kenya - All 47 Counties
    KE: [
        { value: 'baringo', label: 'Baringo' },
        { value: 'bomet', label: 'Bomet' },
        { value: 'bungoma', label: 'Bungoma' },
        { value: 'busia', label: 'Busia' },
        { value: 'elgeyo_marakwet', label: 'Elgeyo-Marakwet' },
        { value: 'embu', label: 'Embu' },
        { value: 'garissa', label: 'Garissa' },
        { value: 'homa_bay', label: 'Homa Bay' },
        { value: 'isiolo', label: 'Isiolo' },
        { value: 'kajiado', label: 'Kajiado' },
        { value: 'kakamega', label: 'Kakamega' },
        { value: 'kericho', label: 'Kericho' },
        { value: 'kiambu', label: 'Kiambu' },
        { value: 'kilifi', label: 'Kilifi' },
        { value: 'kirinyaga', label: 'Kirinyaga' },
        { value: 'kisii', label: 'Kisii' },
        { value: 'kisumu', label: 'Kisumu' },
        { value: 'kitui', label: 'Kitui' },
        { value: 'kwale', label: 'Kwale' },
        { value: 'laikipia', label: 'Laikipia' },
        { value: 'lamu', label: 'Lamu' },
        { value: 'machakos', label: 'Machakos' },
        { value: 'makueni', label: 'Makueni' },
        { value: 'mandera', label: 'Mandera' },
        { value: 'marsabit', label: 'Marsabit' },
        { value: 'meru', label: 'Meru' },
        { value: 'migori', label: 'Migori' },
        { value: 'mombasa', label: 'Mombasa' },
        { value: 'murang_a', label: "Murang'a" },
        { value: 'nairobi', label: 'Nairobi' },
        { value: 'nakuru', label: 'Nakuru' },
        { value: 'nandi', label: 'Nandi' },
        { value: 'narok', label: 'Narok' },
        { value: 'nyamira', label: 'Nyamira' },
        { value: 'nyandarua', label: 'Nyandarua' },
        { value: 'nyeri', label: 'Nyeri' },
        { value: 'samburu', label: 'Samburu' },
        { value: 'siaya', label: 'Siaya' },
        { value: 'taita_taveta', label: 'Taita-Taveta' },
        { value: 'tana_river', label: 'Tana River' },
        { value: 'tharaka_nithi', label: 'Tharaka-Nithi' },
        { value: 'trans_nzoia', label: 'Trans-Nzoia' },
        { value: 'turkana', label: 'Turkana' },
        { value: 'uasin_gishu', label: 'Uasin Gishu' },
        { value: 'vihiga', label: 'Vihiga' },
        { value: 'wajir', label: 'Wajir' },
        { value: 'west_pokot', label: 'West Pokot' },
    ],

    // United States
    US: [
        { value: 'AL', label: 'Alabama' },
        { value: 'AK', label: 'Alaska' },
        { value: 'AZ', label: 'Arizona' },
        { value: 'AR', label: 'Arkansas' },
        { value: 'CA', label: 'California' },
        { value: 'CO', label: 'Colorado' },
        { value: 'CT', label: 'Connecticut' },
        { value: 'DE', label: 'Delaware' },
        { value: 'FL', label: 'Florida' },
        { value: 'GA', label: 'Georgia' },
        { value: 'HI', label: 'Hawaii' },
        { value: 'ID', label: 'Idaho' },
        { value: 'IL', label: 'Illinois' },
        { value: 'IN', label: 'Indiana' },
        { value: 'IA', label: 'Iowa' },
        { value: 'KS', label: 'Kansas' },
        { value: 'KY', label: 'Kentucky' },
        { value: 'LA', label: 'Louisiana' },
        { value: 'ME', label: 'Maine' },
        { value: 'MD', label: 'Maryland' },
        { value: 'MA', label: 'Massachusetts' },
        { value: 'MI', label: 'Michigan' },
        { value: 'MN', label: 'Minnesota' },
        { value: 'MS', label: 'Mississippi' },
        { value: 'MO', label: 'Missouri' },
        { value: 'MT', label: 'Montana' },
        { value: 'NE', label: 'Nebraska' },
        { value: 'NV', label: 'Nevada' },
        { value: 'NH', label: 'New Hampshire' },
        { value: 'NJ', label: 'New Jersey' },
        { value: 'NM', label: 'New Mexico' },
        { value: 'NY', label: 'New York' },
        { value: 'NC', label: 'North Carolina' },
        { value: 'ND', label: 'North Dakota' },
        { value: 'OH', label: 'Ohio' },
        { value: 'OK', label: 'Oklahoma' },
        { value: 'OR', label: 'Oregon' },
        { value: 'PA', label: 'Pennsylvania' },
        { value: 'RI', label: 'Rhode Island' },
        { value: 'SC', label: 'South Carolina' },
        { value: 'SD', label: 'South Dakota' },
        { value: 'TN', label: 'Tennessee' },
        { value: 'TX', label: 'Texas' },
        { value: 'UT', label: 'Utah' },
        { value: 'VT', label: 'Vermont' },
        { value: 'VA', label: 'Virginia' },
        { value: 'WA', label: 'Washington' },
        { value: 'WV', label: 'West Virginia' },
        { value: 'WI', label: 'Wisconsin' },
        { value: 'WY', label: 'Wyoming' },
    ],

    // United Kingdom
    GB: [
        { value: 'england', label: 'England' },
        { value: 'scotland', label: 'Scotland' },
        { value: 'wales', label: 'Wales' },
        { value: 'northern_ireland', label: 'Northern Ireland' },
    ],

    // Canada
    CA: [
        { value: 'AB', label: 'Alberta' },
        { value: 'BC', label: 'British Columbia' },
        { value: 'MB', label: 'Manitoba' },
        { value: 'NB', label: 'New Brunswick' },
        { value: 'NL', label: 'Newfoundland and Labrador' },
        { value: 'NS', label: 'Nova Scotia' },
        { value: 'ON', label: 'Ontario' },
        { value: 'PE', label: 'Prince Edward Island' },
        { value: 'QC', label: 'Quebec' },
        { value: 'SK', label: 'Saskatchewan' },
    ],

    // Australia
    AU: [
        { value: 'NSW', label: 'New South Wales' },
        { value: 'VIC', label: 'Victoria' },
        { value: 'QLD', label: 'Queensland' },
        { value: 'WA', label: 'Western Australia' },
        { value: 'SA', label: 'South Australia' },
        { value: 'TAS', label: 'Tasmania' },
        { value: 'ACT', label: 'Australian Capital Territory' },
        { value: 'NT', label: 'Northern Territory' },
    ],

    // India
    IN: [
        { value: 'AP', label: 'Andhra Pradesh' },
        { value: 'AR', label: 'Arunachal Pradesh' },
        { value: 'AS', label: 'Assam' },
        { value: 'BR', label: 'Bihar' },
        { value: 'CG', label: 'Chhattisgarh' },
        { value: 'GA', label: 'Goa' },
        { value: 'GJ', label: 'Gujarat' },
        { value: 'HR', label: 'Haryana' },
        { value: 'HP', label: 'Himachal Pradesh' },
        { value: 'JK', label: 'Jammu and Kashmir' },
        { value: 'JH', label: 'Jharkhand' },
        { value: 'KA', label: 'Karnataka' },
        { value: 'KL', label: 'Kerala' },
        { value: 'MP', label: 'Madhya Pradesh' },
        { value: 'MH', label: 'Maharashtra' },
        { value: 'MN', label: 'Manipur' },
        { value: 'ML', label: 'Meghalaya' },
        { value: 'MZ', label: 'Mizoram' },
        { value: 'NL', label: 'Nagaland' },
        { value: 'OR', label: 'Odisha' },
        { value: 'PB', label: 'Punjab' },
        { value: 'RJ', label: 'Rajasthan' },
        { value: 'SK', label: 'Sikkim' },
        { value: 'TN', label: 'Tamil Nadu' },
        { value: 'TS', label: 'Telangana' },
        { value: 'TR', label: 'Tripura' },
        { value: 'UP', label: 'Uttar Pradesh' },
        { value: 'UK', label: 'Uttarakhand' },
        { value: 'WB', label: 'West Bengal' },
        { value: 'DL', label: 'Delhi' },
    ],

    // Nigeria - All 36 States
    NG: [
        { value: 'abia', label: 'Abia' },
        { value: 'adamawa', label: 'Adamawa' },
        { value: 'akwa_ibom', label: 'Akwa Ibom' },
        { value: 'anambra', label: 'Anambra' },
        { value: 'bauchi', label: 'Bauchi' },
        { value: 'bayelsa', label: 'Bayelsa' },
        { value: 'benue', label: 'Benue' },
        { value: 'borno', label: 'Borno' },
        { value: 'cross_river', label: 'Cross River' },
        { value: 'delta', label: 'Delta' },
        { value: 'ebonyi', label: 'Ebonyi' },
        { value: 'edo', label: 'Edo' },
        { value: 'ekiti', label: 'Ekiti' },
        { value: 'enugu', label: 'Enugu' },
        { value: 'fct', label: 'Federal Capital Territory (Abuja)' },
        { value: 'gombe', label: 'Gombe' },
        { value: 'imo', label: 'Imo' },
        { value: 'jigawa', label: 'Jigawa' },
        { value: 'kaduna', label: 'Kaduna' },
        { value: 'kano', label: 'Kano' },
        { value: 'katsina', label: 'Katsina' },
        { value: 'kebbi', label: 'Kebbi' },
        { value: 'kogi', label: 'Kogi' },
        { value: 'kwara', label: 'Kwara' },
        { value: 'lagos', label: 'Lagos' },
        { value: 'nasarawa', label: 'Nasarawa' },
        { value: 'niger', label: 'Niger' },
        { value: 'ogun', label: 'Ogun' },
        { value: 'ondo', label: 'Ondo' },
        { value: 'osun', label: 'Osun' },
        { value: 'oyo', label: 'Oyo' },
        { value: 'plateau', label: 'Plateau' },
        { value: 'rivers', label: 'Rivers' },
        { value: 'sokoto', label: 'Sokoto' },
        { value: 'taraba', label: 'Taraba' },
        { value: 'yobe', label: 'Yobe' },
        { value: 'zamfara', label: 'Zamfara' },
    ],

    // South Africa
    ZA: [
        { value: 'gauteng', label: 'Gauteng' },
        { value: 'western_cape', label: 'Western Cape' },
        { value: 'kwazulu_natal', label: 'KwaZulu-Natal' },
        { value: 'eastern_cape', label: 'Eastern Cape' },
        { value: 'limpopo', label: 'Limpopo' },
        { value: 'mpumalanga', label: 'Mpumalanga' },
        { value: 'north_west', label: 'North West' },
        { value: 'free_state', label: 'Free State' },
        { value: 'northern_cape', label: 'Northern Cape' },
    ],

    // Germany
    DE: [
        { value: 'BW', label: 'Baden-Württemberg' },
        { value: 'BY', label: 'Bavaria' },
        { value: 'BE', label: 'Berlin' },
        { value: 'BB', label: 'Brandenburg' },
        { value: 'HB', label: 'Bremen' },
        { value: 'HH', label: 'Hamburg' },
        { value: 'HE', label: 'Hesse' },
        { value: 'MV', label: 'Mecklenburg-Vorpommern' },
        { value: 'NI', label: 'Lower Saxony' },
        { value: 'NW', label: 'North Rhine-Westphalia' },
        { value: 'RP', label: 'Rhineland-Palatinate' },
        { value: 'SL', label: 'Saarland' },
        { value: 'SN', label: 'Saxony' },
        { value: 'ST', label: 'Saxony-Anhalt' },
        { value: 'SH', label: 'Schleswig-Holstein' },
        { value: 'TH', label: 'Thuringia' },
    ],

    // France
    FR: [
        { value: 'ARA', label: 'Auvergne-Rhône-Alpes' },
        { value: 'BFC', label: 'Bourgogne-Franche-Comté' },
        { value: 'BRE', label: 'Brittany' },
        { value: 'CVL', label: 'Centre-Val de Loire' },
        { value: 'COR', label: 'Corsica' },
        { value: 'GES', label: 'Grand Est' },
        { value: 'HDF', label: 'Hauts-de-France' },
        { value: 'IDF', label: 'Île-de-France' },
        { value: 'NOR', label: 'Normandy' },
        { value: 'NAQ', label: 'Nouvelle-Aquitaine' },
        { value: 'OCC', label: 'Occitanie' },
        { value: 'PDL', label: 'Pays de la Loire' },
        { value: 'PAC', label: "Provence-Alpes-Côte d'Azur" },
    ],

    // Brazil
    BR: [
        { value: 'AC', label: 'Acre' },
        { value: 'AL', label: 'Alagoas' },
        { value: 'AP', label: 'Amapá' },
        { value: 'AM', label: 'Amazonas' },
        { value: 'BA', label: 'Bahia' },
        { value: 'CE', label: 'Ceará' },
        { value: 'DF', label: 'Federal District' },
        { value: 'ES', label: 'Espírito Santo' },
        { value: 'GO', label: 'Goiás' },
        { value: 'MA', label: 'Maranhão' },
        { value: 'MT', label: 'Mato Grosso' },
        { value: 'MS', label: 'Mato Grosso do Sul' },
        { value: 'MG', label: 'Minas Gerais' },
        { value: 'PA', label: 'Pará' },
        { value: 'PB', label: 'Paraíba' },
        { value: 'PR', label: 'Paraná' },
        { value: 'PE', label: 'Pernambuco' },
        { value: 'PI', label: 'Piauí' },
        { value: 'RJ', label: 'Rio de Janeiro' },
        { value: 'RN', label: 'Rio Grande do Norte' },
        { value: 'RS', label: 'Rio Grande do Sul' },
        { value: 'RO', label: 'Rondônia' },
        { value: 'RR', label: 'Roraima' },
        { value: 'SC', label: 'Santa Catarina' },
        { value: 'SP', label: 'São Paulo' },
        { value: 'SE', label: 'Sergipe' },
        { value: 'TO', label: 'Tocantins' },
    ],

    // Mexico
    MX: [
        { value: 'AGU', label: 'Aguascalientes' },
        { value: 'BCN', label: 'Baja California' },
        { value: 'BCS', label: 'Baja California Sur' },
        { value: 'CAM', label: 'Campeche' },
        { value: 'CHP', label: 'Chiapas' },
        { value: 'CHH', label: 'Chihuahua' },
        { value: 'COA', label: 'Coahuila' },
        { value: 'COL', label: 'Colima' },
        { value: 'DUR', label: 'Durango' },
        { value: 'GUA', label: 'Guanajuato' },
        { value: 'GRO', label: 'Guerrero' },
        { value: 'HID', label: 'Hidalgo' },
        { value: 'JAL', label: 'Jalisco' },
        { value: 'MEX', label: 'Mexico State' },
        { value: 'MIC', label: 'Michoacán' },
        { value: 'MOR', label: 'Morelos' },
        { value: 'NAY', label: 'Nayarit' },
        { value: 'NLE', label: 'Nuevo León' },
        { value: 'OAX', label: 'Oaxaca' },
        { value: 'PUE', label: 'Puebla' },
        { value: 'QUE', label: 'Querétaro' },
        { value: 'ROO', label: 'Quintana Roo' },
        { value: 'SLP', label: 'San Luis Potosí' },
        { value: 'SIN', label: 'Sinaloa' },
        { value: 'SON', label: 'Sonora' },
        { value: 'TAB', label: 'Tabasco' },
        { value: 'TAM', label: 'Tamaulipas' },
        { value: 'TLA', label: 'Tlaxcala' },
        { value: 'VER', label: 'Veracruz' },
        { value: 'YUC', label: 'Yucatán' },
        { value: 'ZAC', label: 'Zacatecas' },
        { value: 'CMX', label: 'Mexico City' },
    ],

    // China
    CN: [
        { value: 'beijing', label: 'Beijing' },
        { value: 'shanghai', label: 'Shanghai' },
        { value: 'tianjin', label: 'Tianjin' },
        { value: 'chongqing', label: 'Chongqing' },
        { value: 'guangdong', label: 'Guangdong' },
        { value: 'jiangsu', label: 'Jiangsu' },
        { value: 'shandong', label: 'Shandong' },
        { value: 'zhejiang', label: 'Zhejiang' },
        { value: 'henan', label: 'Henan' },
        { value: 'sichuan', label: 'Sichuan' },
        { value: 'hubei', label: 'Hubei' },
        { value: 'hunan', label: 'Hunan' },
        { value: 'anhui', label: 'Anhui' },
        { value: 'hebei', label: 'Hebei' },
        { value: 'liaoning', label: 'Liaoning' },
        { value: 'shaanxi', label: 'Shaanxi' },
        { value: 'fujian', label: 'Fujian' },
        { value: 'shanxi', label: 'Shanxi' },
        { value: 'guizhou', label: 'Guizhou' },
        { value: 'chongqing', label: 'Chongqing' },
        { value: 'jilin', label: 'Jilin' },
        { value: 'gansu', label: 'Gansu' },
        { value: 'inner_mongolia', label: 'Inner Mongolia' },
        { value: 'xinjiang', label: 'Xinjiang' },
        { value: 'jiangxi', label: 'Jiangxi' },
        { value: 'yunnan', label: 'Yunnan' },
        { value: 'guangxi', label: 'Guangxi' },
        { value: 'heilongjiang', label: 'Heilongjiang' },
        { value: 'ningxia', label: 'Ningxia' },
        { value: 'hainan', label: 'Hainan' },
        { value: 'tibet', label: 'Tibet' },
        { value: 'qinghai', label: 'Qinghai' },
    ],

    // Japan
    JP: [
        { value: 'hokkaido', label: 'Hokkaido' },
        { value: 'aomori', label: 'Aomori' },
        { value: 'iwate', label: 'Iwate' },
        { value: 'miyagi', label: 'Miyagi' },
        { value: 'akita', label: 'Akita' },
        { value: 'yamagata', label: 'Yamagata' },
        { value: 'fukushima', label: 'Fukushima' },
        { value: 'ibaraki', label: 'Ibaraki' },
        { value: 'tochigi', label: 'Tochigi' },
        { value: 'gunma', label: 'Gunma' },
        { value: 'saitama', label: 'Saitama' },
        { value: 'chiba', label: 'Chiba' },
        { value: 'tokyo', label: 'Tokyo' },
        { value: 'kanagawa', label: 'Kanagawa' },
        { value: 'niigata', label: 'Niigata' },
        { value: 'toyama', label: 'Toyama' },
        { value: 'ishikawa', label: 'Ishikawa' },
        { value: 'fukui', label: 'Fukui' },
        { value: 'yamanashi', label: 'Yamanashi' },
        { value: 'nagano', label: 'Nagano' },
        { value: 'gifu', label: 'Gifu' },
        { value: 'shizuoka', label: 'Shizuoka' },
        { value: 'aichi', label: 'Aichi' },
        { value: 'mie', label: 'Mie' },
        { value: 'shiga', label: 'Shiga' },
        { value: 'kyoto', label: 'Kyoto' },
        { value: 'osaka', label: 'Osaka' },
        { value: 'hyogo', label: 'Hyogo' },
        { value: 'nara', label: 'Nara' },
        { value: 'wakayama', label: 'Wakayama' },
        { value: 'tottori', label: 'Tottori' },
        { value: 'shimane', label: 'Shimane' },
        { value: 'okayama', label: 'Okayama' },
        { value: 'hiroshima', label: 'Hiroshima' },
        { value: 'yamaguchi', label: 'Yamaguchi' },
        { value: 'tokushima', label: 'Tokushima' },
        { value: 'kagawa', label: 'Kagawa' },
        { value: 'ehime', label: 'Ehime' },
        { value: 'kochi', label: 'Kochi' },
        { value: 'fukuoka', label: 'Fukuoka' },
        { value: 'saga', label: 'Saga' },
        { value: 'nagasaki', label: 'Nagasaki' },
        { value: 'kumamoto', label: 'Kumamoto' },
        { value: 'oita', label: 'Oita' },
        { value: 'miyazaki', label: 'Miyazaki' },
        { value: 'kagoshima', label: 'Kagoshima' },
        { value: 'okinawa', label: 'Okinawa' },
    ],

    // For countries without state data, provide a generic "Region" option
    DEFAULT: [
        { value: 'region', label: 'Region/Province' },
    ],
};

// Get states/counties for a specific country
export const getStatesForCountry = (countryCode) => {
    return COUNTRY_STATES[countryCode] || COUNTRY_STATES.DEFAULT;
};

// Check if country has specific state/county data
export const hasStateData = (countryCode) => {
    return COUNTRY_STATES.hasOwnProperty(countryCode) && countryCode !== 'DEFAULT';
};
